import { Question, Exam, ExamAttempt, Statistics } from '../types';

// Mock data - Replace with your Neon.tech API calls
export const mockQuestions: Question[] = [
  {
    id: '1',
    question_text: 'What is the full form of NEFT?',
    option_a: 'National Electronic Funds Transfer',
    option_b: 'National Electric Funds Transfer',
    option_c: 'New Electronic Funds Transfer',
    option_d: 'National Electronic Finance Transfer',
    correct_answer: 'A',
    subject: 'Banking Awareness',
    topic: 'Payment Systems',
    difficulty: 'easy',
    marks: 1,
    explanation: 'NEFT stands for National Electronic Funds Transfer, which is a nationwide payment system.',
    created_by: '1',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    question_text: 'What is the maximum deposit insurance coverage provided by DICGC?',
    option_a: '₹1,00,000',
    option_b: '₹5,00,000',
    option_c: '₹10,00,000',
    option_d: '₹2,00,000',
    correct_answer: 'B',
    subject: 'Banking Awareness',
    topic: 'Deposit Insurance',
    difficulty: 'medium',
    marks: 2,
    explanation: 'DICGC provides maximum insurance coverage of ₹5,00,000 per depositor per bank.',
    created_by: '1',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    question_text: 'Which of the following is NOT a function of RBI?',
    option_a: 'Monetary Policy',
    option_b: 'Currency Issuance',
    option_c: 'Direct Taxation',
    option_d: 'Bank Regulation',
    correct_answer: 'C',
    subject: 'Banking Awareness',
    topic: 'RBI Functions',
    difficulty: 'medium',
    marks: 2,
    created_by: '1',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    question_text: 'What is 15% of 240?',
    option_a: '30',
    option_b: '36',
    option_c: '42',
    option_d: '45',
    correct_answer: 'B',
    subject: 'Quantitative Aptitude',
    topic: 'Percentage',
    difficulty: 'easy',
    marks: 1,
    created_by: '1',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    question_text: 'If the ratio of ages of A and B is 3:4 and sum of their ages is 35, what is A\'s age?',
    option_a: '15',
    option_b: '20',
    option_c: '25',
    option_d: '30',
    correct_answer: 'A',
    subject: 'Quantitative Aptitude',
    topic: 'Ratio & Proportion',
    difficulty: 'medium',
    marks: 2,
    created_by: '1',
    created_at: '2024-01-01T00:00:00Z',
  },
];

export const mockExams: Exam[] = [
  {
    id: '1',
    title: 'SBI PO Prelims Mock Test 1',
    description: 'Comprehensive mock test for SBI PO Preliminary Examination',
    subject: 'Banking',
    duration_minutes: 60,
    total_marks: 100,
    passing_marks: 40,
    difficulty: 'medium',
    is_active: true,
    created_by: '1',
    created_at: '2024-01-01T00:00:00Z',
    questions: mockQuestions.slice(0, 3),
  },
  {
    id: '2',
    title: 'IBPS Clerk Quantitative Aptitude',
    description: 'Practice test focusing on quantitative aptitude',
    subject: 'Quantitative Aptitude',
    duration_minutes: 45,
    total_marks: 50,
    passing_marks: 20,
    difficulty: 'easy',
    is_active: true,
    created_by: '1',
    created_at: '2024-01-02T00:00:00Z',
    questions: mockQuestions.slice(3, 5),
  },
  {
    id: '3',
    title: 'RRB Banking Awareness Test',
    description: 'Banking awareness test for RRB examinations',
    subject: 'Banking Awareness',
    duration_minutes: 30,
    total_marks: 60,
    passing_marks: 25,
    difficulty: 'hard',
    is_active: true,
    created_by: '1',
    created_at: '2024-01-03T00:00:00Z',
    questions: mockQuestions.slice(0, 3),
  },
];

export const mockAttempts: ExamAttempt[] = [
  {
    id: '1',
    exam_id: '1',
    user_id: '2',
    answers: { '1': 'A', '2': 'B', '3': 'C' },
    score: 3,
    total_marks: 5,
    percentage: 60,
    time_taken_minutes: 45,
    status: 'completed',
    started_at: '2024-01-10T10:00:00Z',
    completed_at: '2024-01-10T10:45:00Z',
  },
];

export const mockStatistics: Statistics = {
  total_users: 1250,
  total_exams: 45,
  total_questions: 2340,
  total_attempts: 5670,
  average_score: 68.5,
  subject_wise_performance: [
    { subject: 'Banking Awareness', avg_score: 72.5, attempts: 1200 },
    { subject: 'Quantitative Aptitude', avg_score: 65.3, attempts: 1500 },
    { subject: 'English Language', avg_score: 70.1, attempts: 1100 },
    { subject: 'Reasoning Ability', avg_score: 68.9, attempts: 1200 },
    { subject: 'Computer Knowledge', avg_score: 75.2, attempts: 670 },
  ],
  recent_attempts: [
    {
      user_name: 'Rahul Sharma',
      exam_title: 'SBI PO Prelims Mock 1',
      score: 85,
      completed_at: '2 hours ago',
    },
    {
      user_name: 'Priya Singh',
      exam_title: 'IBPS Clerk Practice',
      score: 72,
      completed_at: '3 hours ago',
    },
    {
      user_name: 'Amit Kumar',
      exam_title: 'RRB Banking Test',
      score: 68,
      completed_at: '5 hours ago',
    },
  ],
};
